// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAEhzs4liL0k0_Sawn3DM2JaDUGXYDR_Vs',
    appId: '1:581041793774:web:d95bb71974b88cceff21ff',
    messagingSenderId: '581041793774',
    projectId: 'shashwat-flutter',
    authDomain: 'shashwat-flutter.firebaseapp.com',
    storageBucket: 'shashwat-flutter.appspot.com',
    measurementId: 'G-FSPJTPZXQB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyApIXoEAlWJ1J3saVcmeNL4qSxuB3JaStA',
    appId: '1:581041793774:android:1f764f270c0c12e5ff21ff',
    messagingSenderId: '581041793774',
    projectId: 'shashwat-flutter',
    storageBucket: 'shashwat-flutter.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBWIJtQOrbh96OkJpD1fp4L6zSBdw7cRW0',
    appId: '1:581041793774:ios:7a87673a5c4dbca6ff21ff',
    messagingSenderId: '581041793774',
    projectId: 'shashwat-flutter',
    storageBucket: 'shashwat-flutter.appspot.com',
    iosBundleId: 'com.example.flutterTiktokShashwat',
  );
}
