// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDWZTduimV2I7s0wWZrhh6eZZHpMNX7G0s',
    appId: '1:431674141651:web:468d8df2529d37a1381d26',
    messagingSenderId: '431674141651',
    projectId: 'tiktok-2095a',
    authDomain: 'tiktok-2095a.firebaseapp.com',
    storageBucket: 'tiktok-2095a.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAmcP_51NDXpp0ZKCaJCDYvi-fsaBKFVvM',
    appId: '1:431674141651:android:48cda0ef362ac0b9381d26',
    messagingSenderId: '431674141651',
    projectId: 'tiktok-2095a',
    storageBucket: 'tiktok-2095a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDwWABYAzGFF3hTvOft8-wO8_4Ir6RUZ-Q',
    appId: '1:431674141651:ios:58e419daf53b4066381d26',
    messagingSenderId: '431674141651',
    projectId: 'tiktok-2095a',
    storageBucket: 'tiktok-2095a.appspot.com',
    iosBundleId: 'com.example.tiktokTutorial',
  );
}
